# Use root/example as user/password credentials
version: "3.1"

services:
  heart-sms-backend:
    container_name: heart-sms-backend
    image: heartsms/heart-sms-backend
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5050:5050"
    env_file:
      - .db.env
    
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    environment:
      - VUE_APP_API_BASE_URL=localhost:5000
      - VUE_APP_WEBSOCKETS_BASE_URL=localhost:5050
    
  heart-sms-db:
    container_name: heart-sms-db
    image: heartsms/heart-sms-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # Uncomment the below lines for testing
    #ports:
    #  - "127.0.0.1:3306:3306"
    env_file:
      - .db.env
    volumes:
      - mysql:/var/lib/mysql
      
volumes:
  mysql:
