# Use root/example as user/password credentials
version: "3.1"

services:
  heart-sms-backend:
    container_name: heart-sms-backend
    image: heartsms/heart-sms-backend
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .db.env
    
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      # Mount the config directory, then edit/replace web-config.json once the container has started
      - ./heart-web-config:/usr/share/nginx/html/config
 
  heart-sms-db:
    container_name: heart-sms-db
    image: heartsms/heart-sms-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # Uncomment the below lines for testing
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .db.env
    volumes:
      - mysql:/var/lib/mysql

  heart-sms-mqtt:
    container_name: heart-sms-mqtt
    image: iegomez/mosquitto-go-auth
    restart: always
    ports:
      # Keep mqtt local for now, haven't figured out SSL yet
      - "127.0.0.1:1883:1883"
      # This will always be local only
      - "127.0.0.1:5050:5050"
    volumes:
      - ./mosquitto:/etc/mosquitto
      
volumes:
  mysql:
