version: "3.7"

services:
  heart-sms-backend:
    container_name: heart-sms-backend
    image: heartsms/heart-sms-backend
    restart: always
    depends_on: 
      - heart-sms-db
    env_file:
      - .db.env
      - .api.env
    
      
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    init: true
    restart: always
    env_file: 
      # /config/web-config.json is derived from .api.env
      - .api.env

 
  heart-sms-db:
    container_name: heart-sms-db
    image: heartsms/heart-sms-db
    restart: always
    # Uncomment the below lines if you need to access to access the database from the host i.e. for debugging
    # ports:
      # - "127.0.0.1:5432:5432"
    env_file:
      - .db.env
    volumes:
      - db:/var/lib/postgresql/data


  heart-sms-push:
    container_name: heart-sms-push
    image: gotify/server
    env_file:
      - .api.env
    environment:
      # Uncomment the below line to allow anyone to make a gotify account on this server
      # You probably don't want this. Create accounts using the admin account above
      # - GOTIFY_REGISTRATION=true
    volumes:
      - "./gotify/data:/app/data"
      - "./gotify/config.yml:/app/config.yml"


  caddy:
    image: caddy
    container_name: caddy
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      # Path to certs directory (uncomment for production certs)
      # - /path/to/certs:/etc/ssl/certs
      
volumes:
  db:
