version: "3.1"

services:
  heart-sms-backend:
    container_name: heart-sms-backend
    image: heartsms/heart-sms-backend
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .db.env
      - .api.env
    
      
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    env_file: 
      # /config/web-config.json is derived from .api.env
      - .api.env

 
  heart-sms-db:
    container_name: heart-sms-db
    image: heartsms/heart-sms-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # Uncomment the below lines for testing
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .db.env
    volumes:
      - mysql:/var/lib/mysql

  heart-sms-mqtt:
    container_name: heart-sms-mqtt
    image: heartsms/heart-sms-mqtt
    restart: always
    ports:
      # SSL endpoint is exposed directly
      - "8883:8883"
      # Unsecured websockets will always be local only
      - "127.0.0.1:5050:5050"
    #env_file: 
      # /etc/mosquitto/conf.d/go-auth.conf is derived from .api.env
      # Comment this out during development to use unencrypted connection between containers on :5000
    #  - .api.env
    volumes:
      #- ./mqtt/mosquitto:/etc/mosquitto
      - ./certs:/etc/certs
      
volumes:
  mysql:
