version: "3.7"

services:
  heart-sms-backend:
    container_name: heart-sms-backend
    image: heartsms/heart-sms-backend:dev
    command: ["npm", "run", "start-dev"]
    restart: always
    depends_on: 
      - heart-sms-db
    ports:
      # In dev we open this up so the android app (emulator) can get here easily
      - "5000:5000"
    env_file:
      - .db.env.example
      - .api.env.example
  

  # We usually test using heart-sms-web without docker (npm run start-dev)
  heart-sms-web:
   container_name: heart-sms-web
   image: heartsms/heart-sms-web:dev
   init: true
   restart: always
   environment:
     - HEART_API_URL=api.heart.lan
     - HEART_USE_SSL=true
   ports:
     - "127.0.0.1:8081:80"
   env_file: 
     # /config/web-config.json is derived from .api.env
     - .api.env.example

 
  heart-sms-db:
    container_name: heart-sms-db
    image: heartsms/heart-sms-db:dev
    restart: always
    # Uncomment the below lines if you need to access to access the database from the host i.e. for debugging
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .db.env.example
    volumes:
      - db-dev:/var/lib/postgresql/data

  heart-sms-push:
    container_name: heart-sms-push
    image: gotify/server
    ports:
      - 8080:80
    env_file:
      - .api.env.example
    environment:
      - GOTIFY_REGISTRATION=true
    volumes:
      - "./gotify/data:/app/data"
      - "./gotify/config.yml:/app/config.yml"

  caddy:
    image: caddy
    container_name: caddy
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      
volumes:
  db-dev:
