version: "3.7"

services:
  heart-sms-backend:
    container_name: heart-sms-backend
    image: heartsms/heart-sms-backend
    restart: always
    depends_on: 
      - heart-sms-db
      - heart-sms-mqtt
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .db.env
      - .api.env
    
      
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    init: true
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    env_file: 
      # /config/web-config.json is derived from .api.env
      - .api.env

 
  heart-sms-db:
    container_name: heart-sms-db
    image: heartsms/heart-sms-db
    restart: always
    # Uncomment the below lines if you need to access to access the database from the host i.e. for debugging
    # ports:
      # - "127.0.0.1:5432:5432"
    env_file:
      - .db.env
    volumes:
      - db:/var/lib/postgresql/data

  heart-sms-mqtt:
    container_name: heart-sms-mqtt
    image: heartsms/heart-sms-mqtt
    init: true
    restart: always
    ports:
      # Uncomment this line for debugging from the host (unencrypted)
      #- "127.0.0.1:1883:1883"
      # SSL endpoint is exposed directly
      - "8883:8883"
      # Unsecured websockets will always be local only
      - "127.0.0.1:5050:5050"
    env_file: 
      # /etc/mosquitto/conf.d/go-auth.conf is derived from .api.env
      # Comment this out during development to allow unencrypted connection between containers on :5000
      - .api.env
    volumes:
      - ./certs:/etc/certs
      
volumes:
  db:
